# Generated by Django 5.0.6 on 2024-07-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Date of publication'),
        ),
    ]
